name: Release

on:
  release:
    types: [released]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref }}

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool restore

    - name: Build solution
      run: |
        dotnet build --no-restore --configuration Release -v d

    - name: Publish Windows CLI
      run: |
        dotnet publish ./Phoebe.CLI --sc --os win -c Release -p:PublishSingleFile=true

    - name: Upload Windows CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-x64-cli
        path: ./**/publish/Phoebe.CLI.exe

    - name: Upload Nuget artifact
      uses: actions/upload-artifact@v4
      with:
        name: nupkg-build
        path: ./*/bin/Release/*.nupkg

    - name: Upload Thunderstore artifacts
      uses: actions/upload-artifact@v4
      with:
        name: thunderstore-build
        path: ./*/Packages/*.zip

  upload-release-artifacts:
    name: Upload Release Artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v7

      - name: Upload artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} thunderstore-build/*.zip win-x64-cli/Phoebe.CLI/bin/Release/net10.0/win-x64/publish/Phoebe.CLI.exe nupkg-build/*/bin/Release/*.nupkg